### ISSUE TITLE
Routing based on RegEx in addition to hostname

### ISSUE THREAD

**Issue by marthinus-engelbrecht** [cedx/reverse-proxy#2]
Hi,  

I'm liking your reverse proxy a lot. It doesn't exactly serve my purpose though. But before I go off and create another new node module, I was wondering if you would mind adding the ability to route based on ReqEx patterns, for more fine-grained routing based on the "url". So you can do:

````
http://www.somewhere.com/magic -> http://www.magic.com
http://www.somewher.com/realStuff -> http://www.realstuff.com
````

I've hacked your code a bit and got it working. I can fork the repository and send you a pull request if you open too it?

**Comment by cedx** [comment]
I haven't enough time to spend on my Open Source projects, so every contribution is welcome :) Don't hesitate to submit a pull request!

**Comment by marthinus-engelbrecht** [comment]
Cool, forked it. Will make the changes and submit it once I'm done.

**Comment by cedx** [comment]
I close this issue as I do not plan to add this feature (I'm too busy)... but if someone wants to submit a pull request, it would be a good idea because I think this feature is a good one.
