### ISSUE TITLE
multi port support ?

### ISSUE THREAD

**Issue by edeity** [cedx/reverse-proxy#3]
I don't want to open several shell, so can I use like this?
```json
[
 { "port": 80,
  "target": 3000
},
{
 "port": 81,
 "target": 3001
}
]
```

**Comment by cedx** [comment]
From the documentation:
> In order to listen on several ports, all you have to do is use a JSON array or a YAML stream containing a different configuration object for each port to listen. Consequently, each port can have its own settings and routing table.

A detailled code sample: [Multiple ports](https://github.com/cedx/reverse-proxy/blob/master/example/json/multiple_ports.json)
So, what you have done is already good 👍 
Thanks for using this product.
